# Generated by Django 4.1.2 on 2022-11-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='struct',
            old_name='images',
            new_name='img',
        ),
    ]
