# Generated by Django 4.1.2 on 2022-11-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_images_struct_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=250)),
                ('imag', models.ImageField(upload_to='imgs')),
                ('teamdescr', models.TextField()),
            ],
        ),
    ]
